metadata: Fix missing declaration for GNOMELOCALEDIR
metadata/rb-metadata-dbus-service.c: In function ‘main’:
metadata/rb-metadata-dbus-service.c:365:42: error: ‘GNOMELOCALEDIR’ undeclared (first use in this function)
  365 |         bindtextdomain (GETTEXT_PACKAGE, GNOMELOCALEDIR);
      |                                          ^~~~~~~~~~~~~~