backends: Fix traceback in artsearch plugin
Traceback (most recent call last):
  File "/app/lib/rhythmbox/plugins/artsearch/embedded.py", line 46, in discovered_cb
    pixbuf = RB.gst_process_embedded_image(tags, tagname)
  File "/usr/lib/python3.9/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.RB' object has no attribute 'gst_process_embedded_image'

Make sure to process rb-player-gst-helper.h as it used to be in
the autotools days, so we have a binding for
gst_process_embedded_image():
https://gitlab.gnome.org/GNOME/rhythmbox/-/blob/9b7c55544f0f6453fc6b764135cd01ba82168558/bindings/gi/Makefile.am#L37

Closes: #1992