Fix build on x86_32
I got this build failure building 'master' using jhbuild:

    In file included from rb-android-source.c:42:0:
    rb-android-source.c: In function ‘free_space_cb’:
    rb-android-source.c:127:13: error: format ‘%lu’ expects argument of type
    ‘long unsigned int’, but argument 6 has type ‘guint64 {aka long long
    unsigned int}’ [-Werror=format=]
       rb_debug ("capacity: %lu, free space: %lu", priv->storage_capacity_next, priv->storage_free_space_next);
                 ^
    ../../lib/rb-debug.h:41:79: note: in definition of macro ‘rb_debug’
     #define rb_debug(...) rb_debug_realf (__FUNCTION__, __FILE__, __LINE__, TRUE, __VA_ARGS__)
                                                                                   ^
    rb-android-source.c:127:13: error: format ‘%lu’ expects argument of type
    ‘long unsigned int’, but argument 7 has type ‘guint64 {aka long long
    unsigned int}’ [-Werror=format=]
       rb_debug ("capacity: %lu, free space: %lu", priv->storage_capacity_next, priv->storage_free_space_next);
                 ^
    ../../lib/rb-debug.h:41:79: note: in definition of macro ‘rb_debug’
     #define rb_debug(...) rb_debug_realf (__FUNCTION__, __FILE__, __LINE__, TRUE, __VA_ARGS__)
                                                                                   ^
    cc1: all warnings being treated as errors

Fixed by using %G_GUINT64_FORMAT instead of %lu to display the guint64
parameters. The correct % format to use for guint64 depends on the
target libc and architecture, sadly.