shell: Don't use gtk-doc comment style for non-doc
../shell/rb-play-order-shuffle.c:66: Error: RB: Skipping invalid GTK-Doc comment block:
/** TRUE if the query model has been changed */
^