shell: Fix missing declaration for GNOMELOCALEDIR
shell/main.c: In function ‘main’:
shell/main.c:69:42: error: ‘GNOMELOCALEDIR’ undeclared (first use in this function)
   69 |         bindtextdomain (GETTEXT_PACKAGE, GNOMELOCALEDIR);
      |                                          ^~~~~~~~~~~~~~