playlist-manager: Fix crash with libxml2 2.12
The missing include resulted in an implicit function declaration, which
may result in a segmentation fault on startup.

    ../shell/rb-playlist-manager.c: In function ‘rb_playlist_manager_load_playlists’:
    ../shell/rb-playlist-manager.c:374:23: warning: implicit declaration of function ‘xmlParseMemory’ [-Wimplicit-function-declaration]
      374 |                 doc = xmlParseMemory (g_bytes_get_data (data, NULL), g_bytes_get_size (data));
          |                       ^~~~~~~~~~~~~~
    ../shell/rb-playlist-manager.c:374:23: warning: nested extern declaration of ‘xmlParseMemory’ [-Wnested-externs]
    ../shell/rb-playlist-manager.c:374:21: warning: assignment to ‘xmlDocPtr’ {aka ‘struct _xmlDoc *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
      374 |                 doc = xmlParseMemory (g_bytes_get_data (data, NULL), g_bytes_get_size (data));
          |                     ^